Na začetku združimo vsi_katalogi_ready.csv in vikend_akcije_ready.csv v eno tabelo:

In [1]:
import pandas as pd

# Read both CSV files (semicolon as separator)
df1 = pd.read_csv('vsikatalogi_ready.csv', sep=';')
df2 = pd.read_csv('vikend_akcije_ready.csv', sep=';')

# Concatenate the two DataFrames
df_all = pd.concat([df1, df2], ignore_index=True)

# Save to a new CSV file
df_all.to_csv('vse_cene.csv', sep=';', index=False)

Zdaj naredimo še novo tabelo, kjer izbrišemo vse osamelce, da nas ne motijo pri izpisu

In [2]:
# ...existing code...

# Load the merged data
df = pd.read_csv('vse_cene.csv', sep=';')

# Convert price to numeric (in case of any issues)
df['Price (€)'] = pd.to_numeric(df['Price (€)'], errors='coerce')

# Calculate IQR for price
Q1 = df['Price (€)'].quantile(0.25)
Q3 = df['Price (€)'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter out outliers
df_no_outliers = df[(df['Price (€)'] >= lower_bound) & (df['Price (€)'] <= upper_bound)]

# Save to a new CSV file
df_no_outliers.to_csv('vse_cene_no_outliers.csv', sep=';', index=False)

Naredimo poskusno analizo, da vidimo če so podatki v redu

In [3]:
import pandas as pd

# Naložimo podatke brez outlierjev
df = pd.read_csv('vse_cene_no_outliers.csv', sep=';')

# Prikažemo prvih nekaj vrstic
print("Prvih 5 vrstic podatkov:")
display(df.head())

# Osnovne informacije o podatkih
print("\nOsnovne informacije o podatkih:")
display(df.info())

# Preverimo manjkajoče vrednosti
print("\nŠtevilo manjkajočih vrednosti po stolpcih:")
display(df.isnull().sum())

# Pretvorimo stolpec 'Date' v datetime, če je mogoče
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Osnovna statistika za cene
print("\nOsnovna statistika za cene:")
display(df['Price (€)'].describe())

# Število unikatnih trgovin
print("\nŠtevilo unikatnih trgovin:")
display(df['Store'].nunique())
print("Trgovine:", df['Store'].unique())

# Najpogostejši izdelki
print("\nNajpogostejših 10 izdelkov:")
display(df['Product Name'].value_counts().head(10))

# Najpogostejše trgovine
print("\nNajpogostejših 10 trgovin:")
display(df['Store'].value_counts().head(20))

# Število izdelkov skozi čas (leto)
print("\nŠtevilo izdelkov po letih:")
display(df['Date'].dt.year.value_counts().sort_index())

# Povprečna cena po trgovinah
print("\nPovprečna cena po trgovinah:")
display(df.groupby('Store')['Price (€)'].mean().sort_values(ascending=False))

# Povprečna cena po letih
print("\nPovprečna cena po letih:")
display(df.groupby(df['Date'].dt.year)['Price (€)'].mean())

# Povprečna cena po mesecih (v vseh letih skupaj)
print("\nPovprečna cena po mesecih (vseh let skupaj):")
display(df.groupby(df['Date'].dt.month)['Price (€)'].mean())

# Število izdelkov brez datuma
print("\nŠtevilo izdelkov brez datuma:")
display(df['Date'].isnull().sum())

Prvih 5 vrstic podatkov:

,ID,Store,Date,Price (€),Product Name
0,1,Spar,2025-05-20,3.24,Hrenovke hot dog brez ovoja pakirano panvita x...
1,2,Spar,2025-05-20,3.49,Prve slovenske jagode 500g
2,3,Spar,2025-05-20,1.99,Slovenska solata gentile kristalka 1kg
3,4,Spar,2025-05-20,2.99,Krompir pakirano 35g
4,5,Spar,2025-05-13,0.99,Slovenska jabolka zlatni delišes 1kg

Osnovne informacije o podatkih:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20885 entries, 0 to 20884
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            20885 non-null  int64
 1   Store         20885 non-null  object
 2   Date          20851 non-null  object
 3   Price (€)     20885 non-null  float64
 4   Product Name  20885 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 815.9+ KB

None

Število manjkajočih vrednosti po stolpcih:

ID               0
Store            0
Date            34
Price (€)        0
Product Name     0
dtype: int64

Osnovna statistika za cene:

count    20885.000000
mean         2.270311
std          1.811557
min          0.020000
25%          0.990000
50%          1.690000
75%          2.990000
max          8.490000
Name: Price (€), dtype: float64

Število unikatnih trgovin:

16

Trgovine: ['Spar' 'Mercator' 'Lidl' 'Eurospin' 'Tuš' 'Hofer' 'Mana' 'Rutar'
 'E leclerc' 'Perutnina ptuj' 'Nkd' 'Jager' 'Europin' 'Hervis'
 'Pikapolonica' 'Živex']

Najpogostejših 10 izdelkov:

Product Name
Banane                           82
Mango                            61
Ananas                           59
Odojek v kosih                   54
Svinjski vrat brez kosti         49
Šopek vrtnic                     45
Energijski napitek               42
Schwarzwaldska šunka 100 g za    37
Avokado                          36
Banane 1kg                       36
Name: count, dtype: int64

Najpogostejših 10 trgovin:

Store
Hofer             8734
Lidl              6010
Eurospin          2518
Mercator          1857
Tuš               1083
Spar               321
E leclerc          180
Perutnina ptuj     129
Mana                36
Europin              5
Jager                4
Hervis               3
Nkd                  2
Rutar                1
Pikapolonica         1
Živex                1
Name: count, dtype: int64

Število izdelkov po letih:

Date
2014.0    1527
2015.0    2200
2016.0    1762
2017.0    1704
2018.0    1716
2019.0    1562
2020.0    1762
2021.0    2077
2022.0    2406
2023.0    1387
2024.0    1583
2025.0     889
Name: count, dtype: int64

Povprečna cena po trgovinah:

Store
Hervis            7.990000
Pikapolonica      6.740000
Živex             6.490000
Mana              6.051667
Rutar             4.990000
Perutnina ptuj    3.961163
Mercator          2.560086
Spar              2.475639
Tuš               2.365374
Lidl              2.289316
Hofer             2.272401
E leclerc         2.033333
Nkd               1.990000
Eurospin          1.804474
Europin           1.598000
Jager             1.595000
Name: Price (€), dtype: float64

Povprečna cena po letih:

Date
2014.0    2.083563
2015.0    1.746027
2016.0    1.835062
2017.0    2.070153
2018.0    2.174604
2019.0    2.377113
2020.0    2.389052
2021.0    2.215378
2022.0    2.522232
2023.0    2.768435
2024.0    2.713474
2025.0    2.709730
Name: Price (€), dtype: float64

Povprečna cena po mesecih (vseh let skupaj):

Date
1.0     2.252352
2.0     2.286989
3.0     2.290742
4.0     2.279144
5.0     2.330727
6.0     2.164844
7.0     2.249086
8.0     2.109813
9.0     2.317588
10.0    2.200099
11.0    2.264241
12.0    2.426002
Name: Price (€), dtype: float64

Število izdelkov brez datuma:

np.int64(310)

Zdaj pa gremo dalje, prvo bomo pogrupirali podobne izdelke v eno, z uporabo knjižnice rapidfuzz.

In [4]:
import pandas as pd
from rapidfuzz import fuzz, process

# Naloži podatke
df = pd.read_csv('vse_cene_no_outliers.csv', sep=';')

# Pripravi seznam unikatnih imen izdelkov
product_names = df['Product Name'].unique()
canonical_names = []
name_to_canonical = {}

# Prag za podobnost (0-100)
SIMILARITY_THRESHOLD = 85

for name in product_names:
    found = False
    for canon in canonical_names:
        if fuzz.token_set_ratio(name, canon) >= SIMILARITY_THRESHOLD:
            name_to_canonical[name] = canon
            found = True
            break
    if not found:
        canonical_names.append(name)
        name_to_canonical[name] = name

# Dodaj nov stolpec s kanoničnim imenom
df['Product Name Grouped'] = df['Product Name'].map(name_to_canonical)

# Najpogostejših 10 izdelkov po skupinah
print("Najpogostejših 10 izdelkov (po fuzzy skupinah):")
display(df['Product Name Grouped'].value_counts().head(30))

Najpogostejših 10 izdelkov (po fuzzy skupinah):

Product Name Grouped
Banane 1kg                                   123
Rumeni krompir pakiran 10kg                  117
Odojek                                       106
Svinjski vrat brez kosti 1kg                  86
Svinjski zrezki 500 g za                      78
Piščančje krače                               75
Rumena čebula pakirana 10 kg                  74
Mortadela                                     71
Mango cena za kos                             69
Piščančje peruti 400 g za                     68
Piščančji medaljoni 400 g za                  67
Piščančji zrezki 500 g za                     64
Ananas 1kg                                    63
Toaletni papir 3 – slojni 6 rol za            62
Piščančja stegna 600 g za                     60
Energijski napitek s budget 250ml 12 + 12     58
Jogurt na grški način 4 x 125 g za            57
Piščančja bedra 500 g za                      55
Mehki sir v slanici 450 g za                  55
Schwarzwaldska šunka 100 g za                 53
Tekoči jogurt                                 51
Piščančja posebna klobasa poli 350 g za       51
Čevapčiči 950 g za                            51
Mesni narezek                                 50
Piščančji mini file 350 g za                  48
Pršut rezine                                  46
Svinjsko pleče brez kosti postrežno 1kg       45
Klobasa za kuhanje 500 g za                   45
Sončnično olje 1 l za                         45
Šopek vrtnic                                  45
Name: count, dtype: int64

In [5]:
# Analiza na združenih imenih
print("Najpogostejših 10 izdelkov (po skupinah):")
display(df['Product Name Grouped'].value_counts().head(10))

# Povprečna cena po skupinah
print("Povprečna cena po skupinah:")
display(df.groupby('Product Name Grouped')['Price (€)'].mean().sort_values(ascending=False))

Najpogostejših 10 izdelkov (po skupinah):

Product Name Grouped
Banane 1kg                      123
Rumeni krompir pakiran 10kg     117
Odojek                          106
Svinjski vrat brez kosti 1kg     86
Svinjski zrezki 500 g za         78
Piščančje krače                  75
Rumena čebula pakirana 10 kg     74
Mortadela                        71
Mango cena za kos                69
Piščančje peruti 400 g za        68
Name: count, dtype: int64

Povprečna cena po skupinah:

Product Name Grouped
Sveža torta 1kg                                            8.49
Studenec slovenska postrv (ribogojstvo goričar)            8.49
Model za peko crofton                                      8.49
Faks celebration                                           8.49
Gelee royale junior ali junior imunost medex 10 x 9 ml     8.49
                                                           ...
Koper 10 g za                                              0.12
Kvas                                                       0.12
Začimbe v vrečkah                                          0.09
Kajzerice 60 g                                             0.09
Intimni robčki (satessa classic ali sensitive 20 kosov)    0.02
Name: Price (€), Length: 6130, dtype: float64

In [6]:
import pandas as pd
from rapidfuzz import fuzz

# Naloži podatke
df = pd.read_csv('vse_cene_no_outliers.csv', sep=';')

# Pripravi seznam unikatnih imen izdelkov
product_names = df['Product Name'].unique()
canonical_names = []
name_to_canonical = {}

# Prag za podobnost (0-100)
SIMILARITY_THRESHOLD = 85

for name in product_names:
    found = False
    for canon in canonical_names:
        if fuzz.token_set_ratio(name, canon) >= SIMILARITY_THRESHOLD:
            name_to_canonical[name] = canon
            found = True
            break
    if not found:
        canonical_names.append(name)
        name_to_canonical[name] = name

# Dodaj nov stolpec s kanoničnim imenom
df['Product Name Grouped'] = df['Product Name'].map(name_to_canonical)

# Dodaj še en stolpec z ID skupine (številka skupine)
group_ids = {name: idx for idx, name in enumerate(canonical_names)}
df['Product Name Grouped ID'] = df['Product Name Grouped'].map(group_ids)

# Shrani novo tabelo v CSV
df.to_csv('vse_cene_no_outliers_grouped.csv', sep=';', index=False)

Še kratko analizo vseh cen in izdelkov, ki so zdaj pogrupirane

In [7]:
import pandas as pd

# Naložimo podatke z novima stolpcema (združena imena in ID skupine)
df = pd.read_csv('vse_cene_no_outliers_grouped.csv', sep=';')

# Prikažemo prvih nekaj vrstic
print("Prvih 5 vrstic podatkov:")
display(df.head())

# Osnovne informacije o podatkih
print("\nOsnovne informacije o podatkih:")
display(df.info())

# Preverimo manjkajoče vrednosti
print("\nŠtevilo manjkajočih vrednosti po stolpcih:")
display(df.isnull().sum())

# Pretvorimo stolpec 'Date' v datetime, če je mogoče
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Osnovna statistika za cene
print("\nOsnovna statistika za cene:")
display(df['Price (€)'].describe())

# Število unikatnih trgovin
print("\nŠtevilo unikatnih trgovin:")
display(df['Store'].nunique())
print("Trgovine:", df['Store'].unique())

# Najpogostejših 10 izdelkov (po združenih imenih)
print("\nNajpogostejših 10 izdelkov (po skupinah):")
display(df['Product Name Grouped'].value_counts().head(10))

# Najpogostejše trgovine
print("\nNajpogostejših 10 trgovin:")
display(df['Store'].value_counts().head(10))

# Število izdelkov skozi čas (leto)
print("\nŠtevilo izdelkov po letih:")
display(df['Date'].dt.year.value_counts().sort_index())

# Povprečna cena po trgovinah
print("\nPovprečna cena po trgovinah:")
display(df.groupby('Store')['Price (€)'].mean().sort_values(ascending=False))

# Povprečna cena po letih
print("\nPovprečna cena po letih:")
display(df.groupby(df['Date'].dt.year)['Price (€)'].mean())

# Povprečna cena po mesecih (v vseh letih skupaj)
print("\nPovprečna cena po mesecih (vseh let skupaj):")
display(df.groupby(df['Date'].dt.month)['Price (€)'].mean())

# Število izdelkov brez datuma
print("\nŠtevilo izdelkov brez datuma:")
display(df['Date'].isnull().sum())

Prvih 5 vrstic podatkov:

,ID,Store,Date,Price (€),Product Name,Product Name Grouped,Product Name Grouped ID
0,1,Spar,2025-05-20,3.24,Hrenovke hot dog brez ovoja pakirano panvita x...,Hrenovke hot dog brez ovoja pakirano panvita x...,0
1,2,Spar,2025-05-20,3.49,Prve slovenske jagode 500g,Prve slovenske jagode 500g,1
2,3,Spar,2025-05-20,1.99,Slovenska solata gentile kristalka 1kg,Slovenska solata gentile kristalka 1kg,2
3,4,Spar,2025-05-20,2.99,Krompir pakirano 35g,Krompir pakirano 35g,3
4,5,Spar,2025-05-13,0.99,Slovenska jabolka zlatni delišes 1kg,Slovenska jabolka zlatni delišes 1kg,4

Osnovne informacije o podatkih:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20885 entries, 0 to 20884
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       20885 non-null  int64
 1   Store                    20885 non-null  object
 2   Date                     20851 non-null  object
 3   Price (€)                20885 non-null  float64
 4   Product Name             20885 non-null  object
 5   Product Name Grouped     20885 non-null  object
 6   Product Name Grouped ID  20885 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 1.1+ MB

None

Število manjkajočih vrednosti po stolpcih:

ID                          0
Store                       0
Date                       34
Price (€)                   0
Product Name                0
Product Name Grouped        0
Product Name Grouped ID     0
dtype: int64

Osnovna statistika za cene:

count    20885.000000
mean         2.270311
std          1.811557
min          0.020000
25%          0.990000
50%          1.690000
75%          2.990000
max          8.490000
Name: Price (€), dtype: float64

Število unikatnih trgovin:

16

Trgovine: ['Spar' 'Mercator' 'Lidl' 'Eurospin' 'Tuš' 'Hofer' 'Mana' 'Rutar'
 'E leclerc' 'Perutnina ptuj' 'Nkd' 'Jager' 'Europin' 'Hervis'
 'Pikapolonica' 'Živex']

Najpogostejših 10 izdelkov (po skupinah):

Product Name Grouped
Banane 1kg                      123
Rumeni krompir pakiran 10kg     117
Odojek                          106
Svinjski vrat brez kosti 1kg     86
Svinjski zrezki 500 g za         78
Piščančje krače                  75
Rumena čebula pakirana 10 kg     74
Mortadela                        71
Mango cena za kos                69
Piščančje peruti 400 g za        68
Name: count, dtype: int64

Najpogostejših 10 trgovin:

Store
Hofer             8734
Lidl              6010
Eurospin          2518
Mercator          1857
Tuš               1083
Spar               321
E leclerc          180
Perutnina ptuj     129
Mana                36
Europin              5
Name: count, dtype: int64

Število izdelkov po letih:

Date
2014.0    1527
2015.0    2200
2016.0    1762
2017.0    1704
2018.0    1716
2019.0    1562
2020.0    1762
2021.0    2077
2022.0    2406
2023.0    1387
2024.0    1583
2025.0     889
Name: count, dtype: int64

Povprečna cena po trgovinah:

Store
Hervis            7.990000
Pikapolonica      6.740000
Živex             6.490000
Mana              6.051667
Rutar             4.990000
Perutnina ptuj    3.961163
Mercator          2.560086
Spar              2.475639
Tuš               2.365374
Lidl              2.289316
Hofer             2.272401
E leclerc         2.033333
Nkd               1.990000
Eurospin          1.804474
Europin           1.598000
Jager             1.595000
Name: Price (€), dtype: float64

Povprečna cena po letih:

Date
2014.0    2.083563
2015.0    1.746027
2016.0    1.835062
2017.0    2.070153
2018.0    2.174604
2019.0    2.377113
2020.0    2.389052
2021.0    2.215378
2022.0    2.522232
2023.0    2.768435
2024.0    2.713474
2025.0    2.709730
Name: Price (€), dtype: float64

Povprečna cena po mesecih (vseh let skupaj):

Date
1.0     2.252352
2.0     2.286989
3.0     2.290742
4.0     2.279144
5.0     2.330727
6.0     2.164844
7.0     2.249086
8.0     2.109813
9.0     2.317588
10.0    2.200099
11.0    2.264241
12.0    2.426002
Name: Price (€), dtype: float64

Število izdelkov brez datuma:

np.int64(310)

ZDAJ PA ŠE NAREDIMO NOVO TABELO, kjer so pa vpisane vse cene in izdelki top 6 trgovin, in jih tudi tam pogrupiramo

In [8]:
import pandas as pd
from rapidfuzz import fuzz

# Naloži podatke
df = pd.read_csv('vse_cene_no_outliers.csv', sep=';')

# Filtriraj samo top 6 trgovine
top_stores = ['Lidl', 'Mercator', 'Hofer', 'Spar', 'Eurospin', 'Tuš']
df_top = df[df['Store'].isin(top_stores)].copy()

# Pripravi seznam unikatnih imen izdelkov samo za te trgovine
product_names = df_top['Product Name'].unique()
canonical_names = []
name_to_canonical = {}

# Prag za podobnost (0-100)
SIMILARITY_THRESHOLD = 85

for name in product_names:
    found = False
    for canon in canonical_names:
        if fuzz.token_set_ratio(name, canon) >= SIMILARITY_THRESHOLD:
            name_to_canonical[name] = canon
            found = True
            break
    if not found:
        canonical_names.append(name)
        name_to_canonical[name] = name

# Dodaj nov stolpec s kanoničnim imenom samo za top trgovine
df_top['Product Name Grouped'] = df_top['Product Name'].map(name_to_canonical)

# Dodaj še en stolpec z ID skupine (številka skupine)
group_ids = {name: idx for idx, name in enumerate(canonical_names)}
df_top['Product Name Grouped ID'] = df_top['Product Name Grouped'].map(group_ids)

# Prikaži nekaj primerov
print("Primeri združenih imen izdelkov za top trgovine:")
display(df_top[['Product Name', 'Product Name Grouped', 'Store']].head(20))

# Po želji shrani v CSV za nadaljnjo analizo
df_top.to_csv('vse_cene_no_outliers_topstores_grouped.csv', sep=';', index=False)

Primeri združenih imen izdelkov za top trgovine:

,Product Name,Product Name Grouped,Store
0,Hrenovke hot dog brez ovoja pakirano panvita x...,Hrenovke hot dog brez ovoja pakirano panvita x...,Spar
1,Prve slovenske jagode 500g,Prve slovenske jagode 500g,Spar
2,Slovenska solata gentile kristalka 1kg,Slovenska solata gentile kristalka 1kg,Spar
3,Krompir pakirano 35g,Krompir pakirano 35g,Spar
4,Slovenska jabolka zlatni delišes 1kg,Slovenska jabolka zlatni delišes 1kg,Spar
5,Slovenska solata kristalka gentile 1kg,Slovenska solata gentile kristalka 1kg,Spar
6,Slovenski zeleni šparglji 500g,Slovenski zeleni šparglji 500g,Spar
7,Piščančje prsi file ik 500g,Piščančje prsi file ik 500g,Spar
8,Slovenska jabolka idared,Slovenska jabolka idared,Spar
9,Mladi krompir 1kg,Mladi krompir 1kg,Spar
10,Paradižnik grapolo 1kg,Paradižnik grapolo 1kg,Spar
11,Mlado zelje 1kg,Mlado zelje 1kg,Spar
12,Lubenica 1kg,Lubenica 1kg,Spar
13,Instant napitek cedevita več okusov 455g,Instant napitek cedevita več okusov 455g,Spar
14,Slivov paradižnik v lončku 500g,Slivov paradižnik v lončku 500g,Spar
15,Korenje 1kg,Korenje 1kg,Spar
16,Slovenska jabolka topaz 1kg,Slovenska jabolka zlatni delišes 1kg,Spar
17,Mlado zelje 1kg,Mlado zelje 1kg,Spar
18,Krompir pakiran 35kg,Krompir pakirano 35g,Spar
19,Slovenske jabolke idared 1kg,Slovenske jabolke idared 1kg,Spar

In [9]:
import pandas as pd

# Naloži podatke z združenimi imeni za top trgovine
df = pd.read_csv('vse_cene_no_outliers_topstores_grouped.csv', sep=';')

# Število unikatnih skupin izdelkov po trgovinah
print("Število unikatnih skupin izdelkov po trgovinah:")
for store in df['Store'].unique():
    print(f"{store}: {df[df['Store'] == store]['Product Name Grouped'].nunique()}")

# Najpogostejših 10 skupin izdelkov
print("\nNajpogostejših 10 skupin izdelkov:")
display(df['Product Name Grouped'].value_counts().head(10))

# Povprečna cena po skupinah in trgovinah (pivot tabela)
pivot = df.pivot_table(index='Product Name Grouped', columns='Store', values='Price (€)', aggfunc='mean')

print("\nPrimerjava povprečnih cen po skupinah in trgovinah (prvih 10 skupin):")
display(pivot.head(10))

# Povprečna cena po trgovinah (vseh izdelkov)
print("\nPovprečna cena po trgovinah (vseh izdelkov):")
display(df.groupby('Store')['Price (€)'].mean().sort_values())

# Povprečna cena po skupinah (vseh trgovin skupaj)
print("\nPovprečna cena po skupinah (vseh trgovin skupaj):")
display(df.groupby('Product Name Grouped')['Price (€)'].mean().sort_values(ascending=False).head(10))

Število unikatnih skupin izdelkov po trgovinah:
Spar: 158
Mercator: 737
Lidl: 1746
Eurospin: 761
Tuš: 477
Hofer: 3357

Najpogostejših 10 skupin izdelkov:

Product Name Grouped
Banane 1kg                      122
Rumeni krompir pakiran 10kg     117
Odojek                          106
Svinjski vrat brez kosti 1kg     85
Svinjski zrezki 500 g za         78
Rumena čebula pakirana 10 kg     74
Piščančje krače                  71
Mortadela                        70
Mango cena za kos                69
Piščančje peruti 400 g za        66
Name: count, dtype: int64

Primerjava povprečnih cen po skupinah in trgovinah (prvih 10 skupin):

Store,Eurospin,Hofer,Lidl,Mercator,Spar,Tuš
Product Name Grouped,,,,,,
. bio trapist/gavda,NaN,2.39,NaN,NaN,NaN,NaN
1 kg =,NaN,NaN,6.663333,NaN,NaN,NaN
100 konopljino olje,NaN,3.99,NaN,NaN,NaN,5.490
100 sok dana 02 l za,NaN,NaN,NaN,NaN,NaN,0.275
100 sok juicy,NaN,NaN,NaN,NaN,NaN,0.890
12 krogel premera 6 cm ali 9 krogel premer 7 cm za,2.79,NaN,NaN,NaN,NaN,NaN
2 grill piščanca 1kg,2.29,2.19,NaN,NaN,NaN,NaN
2 mini piščanca z drobovino 1kg,NaN,1.79,NaN,NaN,NaN,NaN
25 instant napitek cedevita 900g,NaN,NaN,NaN,NaN,4.93,NaN
25 piščančja prsa file ik 700g,NaN,NaN,NaN,NaN,6.89,NaN

Povprečna cena po trgovinah (vseh izdelkov):

Store
Eurospin    1.804474
Hofer       2.272401
Lidl        2.289316
Tuš         2.365374
Spar        2.475639
Mercator    2.560086
Name: Price (€), dtype: float64

Povprečna cena po skupinah (vseh trgovin skupaj):

Product Name Grouped
Gelee royale junior ali junior imunost medex 10 x 9 ml    8.49
Sveža torta 1kg                                           8.49
Model za peko crofton                                     8.49
Sir jošt president 1kg                                    8.49
Faks celebration                                          8.49
Orada zlatobrov                                           8.49
Komplet prižem 16 delni                                   8.49
Studenec slovenska postrv (ribogojstvo goričar)           8.49
Sir grana padano zorjen več kot 16 mesecev                8.44
Sir šmarski rok 1kg                                       8.39
Name: Price (€), dtype: float64

In [10]:
import pandas as pd

# Naloži podatke z združenimi imeni za top trgovine
df = pd.read_csv('vse_cene_no_outliers_topstores_grouped.csv', sep=';')

# Poišči izdelke, ki se pojavijo v vsaj dveh trgovinah
product_store_counts = df.groupby('Product Name Grouped')['Store'].nunique()
common_products = product_store_counts[product_store_counts >= 2].index

# Filtriraj podatke samo na te izdelke
df_common = df[df['Product Name Grouped'].isin(common_products)].copy()

# Povprečna cena po skupinah in trgovinah (samo za skupne izdelke)
pivot = df_common.pivot_table(index='Product Name Grouped', columns='Store', values='Price (€)', aggfunc='mean')

# Za vsak izdelek poišči trgovino z najnižjo povprečno ceno
cheapest_store = pivot.idxmin(axis=1)
cheapest_count = cheapest_store.value_counts()

print("Kolikokrat je posamezna trgovina najcenejša za skupne izdelke:")
print(cheapest_count)

print("\nDelež najcenejših po trgovinah (%):")
print((cheapest_count / len(pivot) * 100).round(2))

# Povprečna cena po trgovinah za skupne izdelke
print("\nPovprečna cena po trgovinah (samo za skupne izdelke):")
print(pivot.mean().sort_values())

# Prikaz nekaj primerov primerjave cen za skupne izdelke
print("\nPrimerjava cen za nekaj skupnih izdelkov:")
display(pivot.head(10))

Kolikokrat je posamezna trgovina najcenejša za skupne izdelke:
Hofer       275
Lidl        265
Eurospin    117
Tuš          96
Mercator     87
Spar          7
Name: count, dtype: int64

Delež najcenejših po trgovinah (%):
Hofer       32.47
Lidl        31.29
Eurospin    13.81
Tuš         11.33
Mercator    10.27
Spar         0.83
Name: count, dtype: float64

Povprečna cena po trgovinah (samo za skupne izdelke):
Store
Eurospin    1.879366
Lidl        2.035942
Hofer       2.056972
Tuš         2.304164
Mercator    2.472725
Spar        2.747138
dtype: float64

Primerjava cen za nekaj skupnih izdelkov:

Store,Eurospin,Hofer,Lidl,Mercator,Spar,Tuš
Product Name Grouped,,,,,,
100 konopljino olje,NaN,3.990,NaN,NaN,NaN,5.49
2 grill piščanca 1kg,2.290000,2.190,NaN,NaN,NaN,NaN
5-dnevna nagrobna sveča,0.991538,1.490,NaN,NaN,NaN,NaN
Actimel,NaN,3.290,2.577143,NaN,NaN,NaN
Ajdov kruh z orehi,NaN,1.390,1.390000,NaN,NaN,NaN
Ajvar,NaN,1.118,NaN,1.470000,NaN,1.04
Aljaževa salama 100 g za,NaN,1.640,0.590000,NaN,NaN,NaN
Alkoholna pijača johan freitag gin,NaN,1.290,NaN,NaN,NaN,1.29
Alkoholni kis za vlaganje 3l za,0.450000,NaN,1.990000,NaN,NaN,NaN
Alpsko mleko polnomastno ljubljanske mlekarne 6 x 1l 1l,NaN,NaN,NaN,1.529231,6.29,4.99

Tu še stestiramo in probamo urediti izgled same tabele. (trenutno je dokaj grdo če piše npr. Aljaževa salama 100g)
Probajmo odstraniti vse številke, ki bi se lahko navezale na količino.

In [44]:
import pandas as pd
import re

def clean_product_name(name):
    # Remove patterns like '1kg', '10 kg', '500 g', 'cena za kos', 'pakiran', etc., and also "za" and "cena"
    pattern = r'(\d+([.,]\d+)?\s?(kg|g|l|ml|kos|L|ML)\b)|(\bcena\b)|(\bcena za kos\b)|(\bpakiran[ao]?\b)|\bza\b'
    name = re.sub(pattern, '', name, flags=re.IGNORECASE)
    # Remove words with 2 or fewer characters
    name = ' '.join([word for word in name.split() if len(word) > 2])
    # Remove extra spaces left after removal
    name = re.sub(r'\s+', ' ', name)
    return name.strip()

# Example usage on your CSV:
df = pd.read_csv('vse_cene_no_outliers.csv', sep=';')
df['Product Name Cleaned'] = df['Product Name'].apply(clean_product_name)
df.to_csv('vse_cene_cleaned.csv', sep=';', index=False)

Zdaj ko smo uredili osnovno tabelo, pa naredimo še enkrat grupiranja podobnih izdelkov.

In [49]:
import pandas as pd
from rapidfuzz import fuzz

# Load data
df = pd.read_csv('vse_cene_cleaned.csv', sep=';')

# Use the cleaned product names for grouping
product_names = df['Product Name Cleaned'].dropna().unique()
canonical_names = []
name_to_canonical = {}

SIMILARITY_THRESHOLD = 80

# Step 1: Group similar names
for name in product_names:
    found = False
    for canon in canonical_names:
        if fuzz.token_set_ratio(name, canon) >= SIMILARITY_THRESHOLD:
            name_to_canonical[name] = canon
            found = True
            break
    if not found:
        canonical_names.append(name)
        name_to_canonical[name] = name

df['Product Name Grouped'] = df['Product Name Cleaned'].map(name_to_canonical)

# Step 2: For each group, find the shortest name
group_to_names = {}
for name, group in name_to_canonical.items():
    group_to_names.setdefault(group, []).append(name)

group_to_shortest = {group: min(names, key=len) for group, names in group_to_names.items()}

# Step 3: Map each row to the shortest name in its group
df['Product Name Grouped'] = df['Product Name Grouped'].map(group_to_shortest)

# Save the grouped data
df.to_csv('vse_cene_grouped.csv', sep=';', index=False)

# Print number of unique groups
num_groups = df['Product Name Grouped'].nunique()
print(f"Število različnih grupiranih skupin: {num_groups}")

Število različnih grupiranih skupin: 4644

In [51]:
import pandas as pd

# Naloži podatke z združenimi imeni za vse trgovine
df = pd.read_csv('vse_cene_grouped.csv', sep=';')

# Število unikatnih skupin izdelkov po trgovinah
print("Število unikatnih skupin izdelkov po trgovinah:")
for store in df['Store'].unique():
    print(f"{store}: {df[df['Store'] == store]['Product Name Grouped'].nunique()}")

# Najpogostejših 10 skupin izdelkov
print("\nNajpogostejših 10 skupin izdelkov:")
display(df['Product Name Grouped'].value_counts().head(10))

# Povprečna cena po skupinah in trgovinah (pivot tabela)
pivot = df.pivot_table(index='Product Name Grouped', columns='Store', values='Price (€)', aggfunc='mean')

print("\nPrimerjava povprečnih cen po skupinah in trgovinah (prvih 10 skupin):")
display(pivot.head(10))

# Povprečna cena po trgovinah (vseh izdelkov)
print("\nPovprečna cena po trgovinah (vseh izdelkov):")
display(df.groupby('Store')['Price (€)'].mean().sort_values())

# Povprečna cena po skupinah (vseh trgovin skupaj)
print("\nPovprečna cena po skupinah (vseh trgovin skupaj):")
display(df.groupby('Product Name Grouped')['Price (€)'].mean().sort_values(ascending=False).head(10))

# Najpogostejših 10 izdelkov, ki so v vsaj dveh trgovinah
product_store_counts = df.groupby('Product Name Grouped')['Store'].nunique()
common_in_2stores = product_store_counts[product_store_counts >= 2].index
print("\nNajpogostejših 10 izdelkov, ki so v vsaj dveh trgovinah:")
display(df[df['Product Name Grouped'].isin(common_in_2stores)]['Product Name Grouped'].value_counts().head(10))

Število unikatnih skupin izdelkov po trgovinah:
Spar: 137
Mercator: 583
Lidl: 1397
Eurospin: 627
Tuš: 423
Hofer: 2713
Mana: 20
Rutar: 1
E leclerc: 114
Perutnina ptuj: 56
Nkd: 1
Jager: 4
Europin: 5
Hervis: 2
Pikapolonica: 1
Živex: 1

Najpogostejših 10 skupin izdelkov:

Product Name Grouped
Rdeči krompir         134
Svinjski vrat         134
Energijski napitek    132
Banane                124
Piščančje krače       114
Papirnate brisače     106
Odojek                106
Puranji zrezki        105
Puranji medaljoni     101
Ananas                 97
Name: count, dtype: int64

Primerjava povprečnih cen po skupinah in trgovinah (prvih 10 skupin):

Store,E leclerc,Europin,Eurospin,Hervis,Hofer,Jager,Lidl,Mana,Mercator,Nkd,Perutnina ptuj,Pikapolonica,Rutar,Spar,Tuš,Živex
Product Name Grouped,,,,,,,,,,,,,,,,
100 jabolčni sok,NaN,NaN,0.59,NaN,0.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100 konopljino olje,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.49,NaN
100 sok juicy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,NaN
5000 majic,NaN,NaN,NaN,7.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abbott broome masažno mleko: sweet harmony ali vanilla dream,NaN,NaN,NaN,NaN,2.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abc sirni namaz klasičen -22 kos samo,NaN,NaN,NaN,NaN,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abc sveži kremni sir,NaN,NaN,NaN,NaN,NaN,NaN,1.490000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acti snack mešanica impulse pack,NaN,NaN,NaN,NaN,0.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Actimel,NaN,NaN,NaN,NaN,3.29,NaN,2.577143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active med obliži,NaN,NaN,NaN,NaN,0.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Povprečna cena po trgovinah (vseh izdelkov):

Store
Jager             1.595000
Europin           1.598000
Eurospin          1.804474
Nkd               1.990000
E leclerc         2.033333
Hofer             2.272401
Lidl              2.289316
Tuš               2.365374
Spar              2.475639
Mercator          2.560086
Perutnina ptuj    3.961163
Rutar             4.990000
Mana              6.051667
Živex             6.490000
Pikapolonica      6.740000
Hervis            7.990000
Name: Price (€), dtype: float64

Povprečna cena po skupinah (vseh trgovin skupaj):

Product Name Grouped
Komplet prižem delni                               8.49
Orada zlatobrov                                    8.49
Model peko crofton                                 8.49
Gelee royale junior ali junior imunost medex       8.49
Sir jošt president                                 8.49
Faks celebration                                   8.49
Studenec slovenska postrv (ribogojstvo goričar)    8.49
Ženske kavbojke slim fit                           8.39
Sir šmarski rok                                    8.39
Govedina kosu zrezke                               8.29
Name: Price (€), dtype: float64

Najpogostejših 10 izdelkov, ki so v vsaj dveh trgovinah:

Product Name Grouped
Svinjski vrat         134
Energijski napitek    132
Banane                124
Piščančje krače       114
Odojek                106
Papirnate brisače     106
Puranji zrezki        105
Puranji medaljoni     101
Ananas                 97
Svinjsko pleče         96
Name: count, dtype: int64

zdaj pa še za top 6 trgovin

In [18]:
import pandas as pd

# Load the grouped data
df = pd.read_csv('vse_cene_grouped.csv', sep=';')

# Define the top 6 stores
top_stores = ['Mercator', 'Hofer', 'Lidl', 'Spar', 'Eurospin', 'Tuš']

# Filter only rows where Store is in top_stores
df_top6 = df[df['Store'].isin(top_stores)].copy()

# Save to a new CSV file
df_top6.to_csv('vse_cene_grouped_top6.csv', sep=';', index=False)

# Print info
print(f"Število vrstic za top 6 trgovin: {len(df_top6)}")
print("Primeri podatkov za top 6 trgovin:")
print(df_top6.head())

Število vrstic za top 6 trgovin: 20523
Primeri podatkov za top 6 trgovin:
   ID Store        Date  Price (€)  \
0   1  Spar  2025-05-20       3.24
1   2  Spar  2025-05-20       3.49
2   3  Spar  2025-05-20       1.99
3   4  Spar  2025-05-20       2.99
4   5  Spar  2025-05-13       0.99

                                        Product Name  \
0  Hrenovke hot dog brez ovoja pakirano panvita x...
1                         Prve slovenske jagode 500g
2             Slovenska solata gentile kristalka 1kg
3                               Krompir pakirano 35g
4               Slovenska jabolka zlatni delišes 1kg

                          Product Name Cleaned   Product Name Grouped
0  Hrenovke hot dog brez ovoja panvita xxl 1+1               Hrenovke
1                        Prve slovenske jagode              40 jagode
2           Slovenska solata gentile kristalka  Slovenska solata živa
3                                      Krompir                Krompir
4             Slovenska jabolka zlatni delišes      Slovenska jabolka

In [52]:
import pandas as pd

# Load the grouped data for top 6 stores
df = pd.read_csv('vse_cene_grouped.csv', sep=';')
top_stores = ['Mercator', 'Hofer', 'Lidl', 'Spar', 'Eurospin', 'Tuš']
df_top6 = df[df['Store'].isin(top_stores)].copy()

# 1. Koliko izdelkov se prodaja v več trgovinah (skupni izdelki)
product_store_counts = df_top6.groupby('Product Name Grouped')['Store'].nunique()
common_products = product_store_counts[product_store_counts > 1]
print(f"Število izdelkov, ki jih prodaja več kot ena trgovina: {len(common_products)}")
print("Najpogostejši skupni izdelki (top 10):")
print(common_products.sort_values(ascending=False).head(10))

# 2. Koliko različnih unikatnih izdelkov prodaja vsaka trgovina
print("\nŠtevilo unikatnih izdelkov po trgovinah:")
unique_per_store = df_top6.groupby('Store')['Product Name Grouped'].nunique()
print(unique_per_store)

# 3. Najpogostejši izdelki v vsaki trgovini (top 5 za vsako)
print("\nNajpogostejših 5 izdelkov v vsaki trgovini:")
for store in top_stores:
    print(f"\n{store}:")
    print(df_top6[df_top6['Store'] == store]['Product Name Grouped'].value_counts().head(5))

Število izdelkov, ki jih prodaja več kot ena trgovina: 859
Najpogostejši skupni izdelki (top 10):
Product Name Grouped
Paradižnik         6
Breskve            6
Limone             6
Svinjski vrat      6
Hruške             6
Klementine         6
Banane             6
Piščančje krače    6
Nektar             6
Jagode             6
Name: Store, dtype: int64

Število unikatnih izdelkov po trgovinah:
Store
Eurospin     627
Hofer       2713
Lidl        1397
Mercator     583
Spar         137
Tuš          423
Name: Product Name Grouped, dtype: int64

Najpogostejših 5 izdelkov v vsaki trgovini:

Mercator:
Product Name Grouped
Piščančja bedra    40
Riž zlato polje    38
Toaletni papir     33
Svinjski vrat      33
Kava barcaffe      31
Name: count, dtype: int64

Hofer:
Product Name Grouped
Xxl goveje mleto meso        50
Piščančja klobasa rezinah    44
Piščančje krače              42
Mleto mešano meso            36
Svinjski steak               35
Name: count, dtype: int64

Lidl:
Product Name Grouped
Energijski napitek     93
Odojek                 89
Schwarwaldska šunka    60
Jogurt                 55
Ananas                 53
Name: count, dtype: int64

Spar:
Product Name Grouped
Slovenska jabolka        21
Banane                   18
Pomaranče                18
Jagode                   11
Bio paradižnik grozdu     8
Name: count, dtype: int64

Eurospin:
Product Name Grouped
Rdeči krompir              134
Papirnate brisače           79
Rdeča čebula                72
Toaletni papir 3-slojni     69
Banane                      62
Name: count, dtype: int64

Tuš:
Product Name Grouped
Svinjski vrat     57
Sir edam          41
Svinjsko pleče    33
Pomursko mleko    31
Kava barcaffe     18
Name: count, dtype: int64

Premalo skupnih izdelkov, zato se lotimo drugače: Prvo bomo naredili novo tabelo, samo za top 6 trgovin, nato pa naredili fuzzy read se enkrat.

In [53]:
import pandas as pd
from rapidfuzz import fuzz

# 1. Naloži podatke in filtriraj samo top 6 trgovin
top_stores = ['Mercator', 'Hofer', 'Lidl', 'Spar', 'Eurospin', 'Tuš']
df = pd.read_csv('vse_cene_cleaned.csv', sep=';')
df_top6 = df[df['Store'].isin(top_stores)].copy()

# 2. Fuzzy grupiranje na stolpcu 'Product Name Cleaned'
product_names = df_top6['Product Name Cleaned'].dropna().unique()
canonical_names = []
name_to_canonical = {}
SIMILARITY_THRESHOLD = 80


for name in product_names:
    found = False
    for canon in canonical_names:
        if fuzz.token_set_ratio(name, canon) >= SIMILARITY_THRESHOLD:
            name_to_canonical[name] = canon
            found = True
            break
    if not found:
        canonical_names.append(name)
        name_to_canonical[name] = name

df_top6['Product Name Grouped'] = df_top6['Product Name Cleaned'].map(name_to_canonical)

# Najdi najkrajše ime v vsaki skupini
group_to_names = {}
for name, group in name_to_canonical.items():
    group_to_names.setdefault(group, []).append(name)
group_to_shortest = {group: min(names, key=len) for group, names in group_to_names.items()}

# Zamenjaj v stolpcu za najkrajše ime
df_top6['Product Name Grouped'] = df_top6['Product Name Grouped'].map(group_to_shortest)

# Shrani novo tabelo
df_top6.to_csv('vse_cene_cleaned_top6_grouped.csv', sep=';', index=False)

print("Tabela za top 6 trgovin z grupiranimi izdelki je shranjena kot vse_cene_cleaned_top6_grouped.csv")

Tabela za top 6 trgovin z grupiranimi izdelki je shranjena kot vse_cene_cleaned_top6_grouped.csv

Naredimo še enkrat eno hitro analizo, da vidimo če so podatki v redu urejeni

In [54]:
import pandas as pd

# Load the grouped data for top 6 stores
df = pd.read_csv('vse_cene_cleaned_top6_grouped.csv', sep=';')

# 1. Število unikatnih izdelkov (originalna imena)
num_unique_items = df['Product Name'].nunique()
print(f"Število unikatnih izdelkov (original): {num_unique_items}")

# 2. Število grupiranih izdelkov (po fuzzy grupiranju)
num_grouped_items = df['Product Name Grouped'].nunique()
print(f"Število grupiranih izdelkov: {num_grouped_items}")

# 3. Najpogostejših 10 grupiranih izdelkov
print("\nNajpogostejših 10 grupiranih izdelkov:")
print(df['Product Name Grouped'].value_counts().head(10))

# 4. Najpogostejši unikatni izdelki po trgovinah (top 5 za vsako)
print("\nNajpogostejših 5 grupiranih izdelkov v vsaki trgovini:")
for store in df['Store'].unique():
    print(f"\n{store}:")
    print(df[df['Store'] == store]['Product Name Grouped'].value_counts().head(5))

Število unikatnih izdelkov (original): 10957
Število grupiranih izdelkov: 4574

Najpogostejših 10 grupiranih izdelkov:
Product Name Grouped
Rdeči krompir         134
Svinjski vrat         133
Energijski napitek    132
Banane                123
Piščančje krače       109
Odojek                106
Papirnate brisače     106
Puranji zrezki        102
Svinjsko pleče         95
Puranji medaljoni      95
Name: count, dtype: int64

Najpogostejših 5 grupiranih izdelkov v vsaki trgovini:

Spar:
Product Name Grouped
Slovenska jabolka        21
Banane                   18
Pomaranče                18
Jagode                   11
Bio paradižnik grozdu     8
Name: count, dtype: int64

Mercator:
Product Name Grouped
Piščančja bedra    40
Riž zlato polje    38
Toaletni papir     33
Svinjski vrat      33
Kava barcaffe      31
Name: count, dtype: int64

Lidl:
Product Name Grouped
Energijski napitek     93
Odojek                 89
Schwarwaldska šunka    60
Jogurt                 55
Ananas                 53
Name: count, dtype: int64

Eurospin:
Product Name Grouped
Rdeči krompir              134
Papirnate brisače           79
Rdeča čebula                72
Toaletni papir 3-slojni     69
Banane                      62
Name: count, dtype: int64

Tuš:
Product Name Grouped
Svinjski vrat     57
Sir edam          41
Svinjsko pleče    33
Pomursko mleko    31
Kava barcaffe     18
Name: count, dtype: int64

Hofer:
Product Name Grouped
Xxl goveje mleto meso        50
Piščančja klobasa rezinah    44
Piščančje krače              42
Mleto mešano meso            36
Svinjski steak               35
Name: count, dtype: int64

In [55]:
import pandas as pd

# Load the grouped data for top 6 stores
df = pd.read_csv('vse_cene_cleaned_top6_grouped.csv', sep=';')

# Poišči izdelke, ki se pojavijo v vsaj dveh trgovinah
product_store_counts = df.groupby('Product Name Grouped')['Store'].nunique()
common_in_2stores = product_store_counts[product_store_counts >= 2].index

print("\nNajpogostejših 10 grupiranih izdelkov, ki so v vsaj dveh trgovinah:")
print(df[df['Product Name Grouped'].isin(common_in_2stores)]['Product Name Grouped'].value_counts().head(10))

Najpogostejših 10 grupiranih izdelkov, ki so v vsaj dveh trgovinah:
Product Name Grouped
Svinjski vrat         133
Energijski napitek    132
Banane                123
Piščančje krače       109
Odojek                106
Papirnate brisače     106
Puranji zrezki        102
Puranji medaljoni      95
Svinjsko pleče         95
Ananas                 90
Name: count, dtype: int64

In [56]:
import pandas as pd

# Load the grouped data for top 6 stores
df = pd.read_csv('vse_cene_cleaned_top6_grouped.csv', sep=';')

stores = df['Store'].unique()

for store in stores:
    # Izdelki, ki se pojavijo samo v tej trgovini
    items_in_store = set(df[df['Store'] == store]['Product Name Grouped'])
    items_in_other = set(df[df['Store'] != store]['Product Name Grouped'])
    unique_items = items_in_store - items_in_other

    # Preštej pojavitve teh unikatnih izdelkov v tej trgovini
    counts = df[(df['Store'] == store) & (df['Product Name Grouped'].isin(unique_items))]['Product Name Grouped'].value_counts().head(5)

    print(f"\nTop 5 most common unique items in store {store}:")
    for name, count in counts.items():
        print(f"{name}: {count}")

Top 5 most common unique items in store Spar:
Šopki: 3
Pivo staropramen alk: 3
Spar natur*pur bio maslo: 2
Spar veggie bio napitek: 2
Rdeči radič: 2

Top 5 most common unique items in store Mercator:
Sok happy day: 15
Kavanescafe: 14
Kava loka: 10
Flips smoki: 9
Piščančji zrezek natur: 8

Top 5 most common unique items in store Lidl:
Panache: 45
Šopek vrtnic: 45
Kmečka šunka: 43
Dimljen topljeni sir: 30
Krem rezina: 26

Top 5 most common unique items in store Eurospin:
Rdeči krompir: 134
Kmečki pršut: 43
Barjene klobase: 32
Vžigalne kocke: 29
Speck dimljeno sušeno stegno: 22

Top 5 most common unique items in store Tuš:
Pomursko mleko: 31
Pijača dana: 17
Biskvit jaffa: 11
Surovo maslo: 8
Biskvit barni: 6

Top 5 most common unique items in store Hofer:
Blejsa kremšnita: 23
Puranje krače: 22
Sveža torta: 20
Lovke orašjega lignja: 19
Prej:: 19